### ISSUE TITLE
Inconsistent header names

### ISSUE THREAD

**Issue by jstaursky** [TomNisbet/asm85#4]
not a big deal but FYI your `make` cmd does not work as is. Seems that in some places you call for the header `"SymbolTable.h"` and other places `"symboltable.h"`. Similiar situation goes for `scanner.h`.
I did `cp scanner.h Scanner.h` and sim to get around this but thought you should know.

**Comment by TomNisbet** [comment]
Should be fixed now.  Thanks for pointing it out.
